services:
  - type: web
    name: farmora-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: PORT
        value: "10000"
      - key: WEATHER_API_KEY
        value: "7a24cc4e1e02ad6716da7411179e2696"
